In [1]:
import numpy as np

In [2]:
c1 = np.array([1, 0, -1]).reshape(-1, 1)
c2 = np.array([-1, 2, 1]).reshape(-1, 1)
C = np.concatenate([c1, c2], axis = 1).astype(float)
C

array([[ 1., -1.],
       [ 0.,  2.],
       [-1.,  1.]])

In [3]:
d1 = np.array([1, 0, -1]).reshape(-1, 1)
d2 = np.array([2, 1, 4]).reshape(-1, 1)
d3 = np.array([3, 1, 3]).reshape(-1, 1)
D = np.concatenate([d1, d2, d3], axis = 1).astype(float)
D

array([[ 1.,  2.,  3.],
       [ 0.,  1.,  1.],
       [-1.,  4.,  3.]])

In [5]:
D@C

array([[-2.,  6.],
       [-1.,  3.],
       [-4., 12.]])