In [1]:
import numpy as np

In [2]:
r1 = np.array([2, -1, 1]).reshape(1,-1)
r2 = np.array([-1, 2, 0]).reshape(1,-1)
M = np.array([r1,r2]).reshape(2,-1).astype(float)
M

array([[ 2., -1.,  1.],
       [-1.,  2.,  0.]])

In [3]:
M[1] = M[1] +  M[0]/2
M

array([[ 2. , -1. ,  1. ],
       [ 0. ,  1.5,  0.5]])

In [4]:
M[1] = M[1]/1.5
M

array([[ 2.        , -1.        ,  1.        ],
       [ 0.        ,  1.        ,  0.33333333]])

In [5]:
M[0] = M[0]/2
M

array([[ 1.        , -0.5       ,  0.5       ],
       [ 0.        ,  1.        ,  0.33333333]])

In [6]:
d = 1/3
d

0.3333333333333333

In [7]:
c = 0.5 + 0.5*d
c

0.6666666666666666