In [1]:
import numpy as np

Exercise 1: Prove that W = [21, -6, 15] is a linear combination of vectors v1, v2, v3 (the columns in the matrix below)

In [2]:
r1 = np.array([2, 1, 0, 21]).reshape(1,-1)
r2 = np.array([1, -1, -1, -6]).reshape(1,-1)
r3 = np.array([3, 0, -1, 15]).reshape(1,-1)
M = np.array([r1,r2,r3]).reshape(3,-1)
M = np.array([r1,r2,r3]).reshape(3,-1).astype(float)
M

array([[ 2.,  1.,  0., 21.],
       [ 1., -1., -1., -6.],
       [ 3.,  0., -1., 15.]])

In [3]:
M[0] = M[0] * 0.5
M

array([[ 1. ,  0.5,  0. , 10.5],
       [ 1. , -1. , -1. , -6. ],
       [ 3. ,  0. , -1. , 15. ]])

In [4]:
M[1] = M[1] - M[0]
M[2] = M[2] - 3*M[0]
M

array([[  1. ,   0.5,   0. ,  10.5],
       [  0. ,  -1.5,  -1. , -16.5],
       [  0. ,  -1.5,  -1. , -16.5]])

In [5]:
M[1] = M[1] / -1.5
M

array([[  1.        ,   0.5       ,   0.        ,  10.5       ],
       [ -0.        ,   1.        ,   0.66666667,  11.        ],
       [  0.        ,  -1.5       ,  -1.        , -16.5       ]])

In [6]:
M[0] = M[0] - 0.5*M[1]
M[2] = M[2] + 1.5*M[1]
M

array([[ 1.        ,  0.        , -0.33333333,  5.        ],
       [-0.        ,  1.        ,  0.66666667, 11.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

Exercise 2: v1 = [1, 3, 1], v2 = [3, 10, 2]. Can you write w = [1, 5, -1] as a linear combination

In [7]:
r1 = np.array([1, 3, 1]).reshape(-1, 1)
r2 = np.array([3, 10, 2]).reshape(-1, 1)
r3 = np.array([1, 5, -1]).reshape(-1, 1)
M = np.concatenate([r1,r2, r3], axis = 1).astype(float)
M

array([[ 1.,  3.,  1.],
       [ 3., 10.,  5.],
       [ 1.,  2., -1.]])

In [8]:
M[1] = M[1] - 3*M[0]
M[2] = M[2] - M[0]
M

array([[ 1.,  3.,  1.],
       [ 0.,  1.,  2.],
       [ 0., -1., -2.]])

In [9]:
M[0] = M[0] - 3*M[1]
M[2] = M[2] + M[1]
M

array([[ 1.,  0., -5.],
       [ 0.,  1.,  2.],
       [ 0.,  0.,  0.]])

In [10]:
r1 = -5 * np.array([1, 3, 1]).reshape(-1, 1)
r2 = 2 * np.array([3, 10, 2]).reshape(-1, 1)

In [11]:
r1 + r2

array([[ 1],
       [ 5],
       [-1]])

Exercise 3:

<img src="images/vectors_span.PNG">

In [12]:
r1 = np.array([1, 1, 0]).reshape(-1, 1)
r2 = np.array([0, -1, 2]).reshape(-1, 1)
r3 = np.array([-1, -2, 3]).reshape(-1, 1)
r4 = np.array([-2, -5, 8]).reshape(-1, 1)
r5 = np.array([3, 1, 3]).reshape(-1, 1)
M = np.concatenate([r1,r2, r3, r4, r5], axis = 1).astype(float)
M

array([[ 1.,  0., -1., -2.,  3.],
       [ 1., -1., -2., -5.,  1.],
       [ 0.,  2.,  3.,  8.,  3.]])

In [13]:
M[1] = M[1] - M[0]
M

array([[ 1.,  0., -1., -2.,  3.],
       [ 0., -1., -1., -3., -2.],
       [ 0.,  2.,  3.,  8.,  3.]])

In [14]:
M[1] = M[1]/-1
M

array([[ 1.,  0., -1., -2.,  3.],
       [-0.,  1.,  1.,  3.,  2.],
       [ 0.,  2.,  3.,  8.,  3.]])

In [15]:
M[2] = M[2] - 2*M[1]
M

array([[ 1.,  0., -1., -2.,  3.],
       [-0.,  1.,  1.,  3.,  2.],
       [ 0.,  0.,  1.,  2., -1.]])

In [16]:
M[0] = M[0] + M[2]
M[1] = M[1] - M[2]
M

array([[ 1.,  0.,  0.,  0.,  2.],
       [-0.,  1.,  0.,  1.,  3.],
       [ 0.,  0.,  1.,  2., -1.]])

The above is consistent, as there is no row of all zeros followed by a non-zero in the right column. Therefore, w is in the span of the given set of vectors.

