In [1]:
import numpy as np

Excersise 1:

In [2]:
r1 = np.array([-1, 0, 2]).reshape(1,-1)
r2 = np.array([2, -1, 1]).reshape(1,-1)
r3 = np.array([3, 1, -1]).reshape(1,-1)
A = np.array([r1,r2,r3]).reshape(3,-1).astype(float)
A

array([[-1.,  0.,  2.],
       [ 2., -1.,  1.],
       [ 3.,  1., -1.]])

In [3]:
A.shape

(3, 3)

In [4]:
x = np.array([-1, 2, 1]).reshape(-1,1)
x

array([[-1],
       [ 2],
       [ 1]])

In [5]:
A @ x

array([[ 3.],
       [-3.],
       [-2.]])

In [6]:
np.matmul(A, x)

array([[ 3.],
       [-3.],
       [-2.]])

Via Linear Transformations

In [7]:
(A[:, 0] * x[0]).reshape(-1, 1) + \
(A[:, 1] * x[1]).reshape(-1, 1) + \
(A[:, 2] * x[2]).reshape(-1, 1)

array([[ 3.],
       [-3.],
       [-2.]])

Via Dot-Product

In [8]:
np.array([np.dot(A[0], x),
          np.dot(A[1], x),
          np.dot(A[2], x)
         ]).reshape(-1,1)

array([[ 3.],
       [-3.],
       [-2.]])

Excersise 2:

<img src="images/matrix_vector1.PNG">

In [9]:
c1 = np.array([1, 1, 3]).reshape(-1, 1)
c2 = np.array([2, 3, -1]).reshape(-1, 1)
c3 = np.array([3, 2, 16]).reshape(-1, 1)
A = np.concatenate([c1, c2, c3], axis = 1).astype(float)
A

array([[ 1.,  2.,  3.],
       [ 1.,  3.,  2.],
       [ 3., -1., 16.]])

In [10]:
A[1] = A[1] - A[0]
A[2] = A[2] - 3*A[0]
A

array([[ 1.,  2.,  3.],
       [ 0.,  1., -1.],
       [ 0., -7.,  7.]])

In [11]:
A[0] = A[0] - 2*A[1]
A[2] = A[2] + 7*A[1]
A

array([[ 1.,  0.,  5.],
       [ 0.,  1., -1.],
       [ 0.,  0.,  0.]])

In [12]:
x = np.array([5, -1]).reshape(-1, 1)
x

array([[ 5],
       [-1]])

Check Result

In [13]:
A = np.concatenate([c1, c2], axis = 1).astype(float)

In [14]:
assert (A @ x == np.array([[ 3.],[ 2.],[16.]])).all()

Excersise 3:

<img src="images/matrix_vector2.PNG">

In [15]:
c1 = np.array([1, 1, 3]).reshape(-1, 1)
c2 = np.array([2, 3, -1]).reshape(-1, 1)
c3 = np.array([3, -4, 7]).reshape(-1, 1)
A = np.concatenate([c1, c2, c3], axis = 1).astype(float)
A

array([[ 1.,  2.,  3.],
       [ 1.,  3., -4.],
       [ 3., -1.,  7.]])

In [16]:
A[1] = A[1] - A[0]
A[2] = A[2] - 3*A[0]
A

array([[ 1.,  2.,  3.],
       [ 0.,  1., -7.],
       [ 0., -7., -2.]])

In [17]:
A[0] = A[0] - 2*A[1]
A[2] = A[2] + 7*A[1]
A

array([[  1.,   0.,  17.],
       [  0.,   1.,  -7.],
       [  0.,   0., -51.]])

Matrix is inconsistent

In [18]:
x = np.array([0, 0, 0, 0]).reshape(-1, 1)

In [19]:
x

array([[0],
       [0],
       [0],
       [0]])

Excersise 4:

In [20]:
r1 = np.array([1, 1, 0, -1, 0]).reshape(1,-1)
r2 = np.array([5, 6, -1, 1, 0]).reshape(1,-1)
A = np.array([r1,r2]).reshape(2,-1).astype(float)
A

array([[ 1.,  1.,  0., -1.,  0.],
       [ 5.,  6., -1.,  1.,  0.]])

In [21]:
A[1] = A[1] - 5*A[0]
A

array([[ 1.,  1.,  0., -1.,  0.],
       [ 0.,  1., -1.,  6.,  0.]])

In [22]:
A[0] = A[0] - A[1]
A

array([[ 1.,  0.,  1., -7.,  0.],
       [ 0.,  1., -1.,  6.,  0.]])