In [2]:
import numpy as np

## Ex 1:

In [3]:
c1 = np.array([1, 0, -1]).reshape(-1, 1)
c2 = np.array([2, 1, 4]).reshape(-1, 1)
c3 = np.array([3, 1, 3]).reshape(-1, 1)
c4 = np.array([1, -1, -7]).reshape(-1, 1)
M = np.concatenate([c1, c2, c3, c4], axis = 1).astype(float)
M

array([[ 1.,  2.,  3.,  1.],
       [ 0.,  1.,  1., -1.],
       [-1.,  4.,  3., -7.]])

In [4]:
M[2] = M[2] + M[0]
M

array([[ 1.,  2.,  3.,  1.],
       [ 0.,  1.,  1., -1.],
       [ 0.,  6.,  6., -6.]])

In [5]:
M[0] = M[0] - 2*M[1]
M[2] = M[2] - 6*M[1]
M

array([[ 1.,  0.,  1.,  3.],
       [ 0.,  1.,  1., -1.],
       [ 0.,  0.,  0.,  0.]])

## Ex 2:

In [6]:
c1 = np.array([1, 0, -1]).reshape(-1, 1)
c2 = np.array([2, 1, 4]).reshape(-1, 1)
c3 = np.array([3, 1, 3]).reshape(-1, 1)
c4 = np.array([2, -1, 0]).reshape(-1, 1)
M = np.concatenate([c1, c2, c3, c4], axis = 1).astype(float)
M

array([[ 1.,  2.,  3.,  2.],
       [ 0.,  1.,  1., -1.],
       [-1.,  4.,  3.,  0.]])

In [7]:
M[2] = M[2] + M[0]
M

array([[ 1.,  2.,  3.,  2.],
       [ 0.,  1.,  1., -1.],
       [ 0.,  6.,  6.,  2.]])

In [8]:
M[0] = M[0] - 2*M[1]
M[2] = M[2] - 6*M[1]
M

array([[ 1.,  0.,  1.,  4.],
       [ 0.,  1.,  1., -1.],
       [ 0.,  0.,  0.,  8.]])

## Ex 3:

<img src="images/image_of_LT.PNG">

In [9]:
c1 = np.array([1, 0, -1]).reshape(-1, 1)
c2 = np.array([2, 1, 4]).reshape(-1, 1)
c3 = np.array([3, 1, 3]).reshape(-1, 1)
M = np.concatenate([c1, c2, c3], axis = 1).astype(float)
M

array([[ 1.,  2.,  3.],
       [ 0.,  1.,  1.],
       [-1.,  4.,  3.]])

In [10]:
M[2] = M[2] + M[0]
M

array([[1., 2., 3.],
       [0., 1., 1.],
       [0., 6., 6.]])

In [11]:
M[0] = M[0] - 2*M[1]
M[2] = M[2] - 6*M[1]
M

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 0.]])

For example lets do w = [2, -1, 0 ]

In [12]:
c1 = np.array([1, 0, -1]).reshape(-1, 1)
c2 = np.array([2, 1, 4]).reshape(-1, 1)
c3 = np.array([3, 1, 3]).reshape(-1, 1)
c4 = np.array([2, -1, 0]).reshape(-1, 1)
M = np.concatenate([c1, c2, c3, c4], axis = 1).astype(float)
M

array([[ 1.,  2.,  3.,  2.],
       [ 0.,  1.,  1., -1.],
       [-1.,  4.,  3.,  0.]])

In [13]:
M[2] = M[2] + M[0]
M[0] = M[0] - 2*M[1]
M[2] = M[2] - 6*M[1]
M

array([[ 1.,  0.,  1.,  4.],
       [ 0.,  1.,  1., -1.],
       [ 0.,  0.,  0.,  8.]])

## Ex 4:

<img src="images/kernel_LT.PNG">

In [16]:
c1 = np.array([1, 0, -1, 2]).reshape(-1, 1)
c2 = np.array([2, 1, 1, -1]).reshape(-1, 1)
c3 = np.array([5, 2, 1, 0]).reshape(-1, 1)
M = np.concatenate([c1, c2, c3], axis = 1).astype(float)
M

array([[ 1.,  2.,  5.],
       [ 0.,  1.,  2.],
       [-1.,  1.,  1.],
       [ 2., -1.,  0.]])

In [17]:
M[2] = M[2] + M[0]
M[3] = M[3] + -2*M[0]
M

array([[  1.,   2.,   5.],
       [  0.,   1.,   2.],
       [  0.,   3.,   6.],
       [  0.,  -5., -10.]])

In [18]:
M[0] = M[0] - 2*M[1]
M[2] = M[2] - 3*M[1]
M[3] = M[3] + 5*M[1]
M

array([[1., 0., 1.],
       [0., 1., 2.],
       [0., 0., 0.],
       [0., 0., 0.]])

There are free variables so \
[ \
-x3 \
-2x3 \
x3 \
]

In [20]:
x3 = 3
x = np.array([-1*x3, -2*x3, x3]).reshape(-1, 1)
x

array([[-3],
       [-6],
       [ 3]])

In [21]:
c1 = np.array([1, 0, -1, 2]).reshape(-1, 1)
c2 = np.array([2, 1, 1, -1]).reshape(-1, 1)
c3 = np.array([5, 2, 1, 0]).reshape(-1, 1)
M = np.concatenate([c1, c2, c3], axis = 1).astype(float)
M

array([[ 1.,  2.,  5.],
       [ 0.,  1.,  2.],
       [-1.,  1.,  1.],
       [ 2., -1.,  0.]])

In [22]:
M @ x

array([[0.],
       [0.],
       [0.],
       [0.]])