In [1]:
import numpy as np

## Ex 1:

<img src="images/independence.PNG">

In [2]:
c1 = np.array([1, -1, 0, 0]).reshape(-1, 1)
c2 = np.array([2, -1, 3, 5]).reshape(-1, 1)
c3 = np.array([-3, 3, 0, 0]).reshape(-1, 1)
M = np.concatenate([c1, c2, c3], axis = 1).astype(float)
M

array([[ 1.,  2., -3.],
       [-1., -1.,  3.],
       [ 0.,  3.,  0.],
       [ 0.,  5.,  0.]])

In [3]:
M[1] = M[1] + M[0]
M

array([[ 1.,  2., -3.],
       [ 0.,  1.,  0.],
       [ 0.,  3.,  0.],
       [ 0.,  5.,  0.]])

In [4]:
M[0] = M[0] - 2*M[1]
M[2] = M[2] - 3*M[1]
M[3] = M[3] - 5*M[1]
M

array([[ 1.,  0., -3.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

There are free variables so linearly dependent

Example of such scalars:

In [5]:
c1 = np.array([1, -1, 0, 0]).reshape(-1, 1)
c2 = np.array([2, -1, 3, 5]).reshape(-1, 1)
c3 = np.array([-3, 3, 0, 0]).reshape(-1, 1)
M = np.concatenate([c1, c2, c3], axis = 1).astype(float)
M

array([[ 1.,  2., -3.],
       [-1., -1.,  3.],
       [ 0.,  3.,  0.],
       [ 0.,  5.,  0.]])

In [6]:
M @ np.array([15, -0, 5]).reshape(-1, 1)

array([[0.],
       [0.],
       [0.],
       [0.]])

## Ex 2:

<img src="images/independence2.PNG">

In [7]:
c1 = np.array([1, -1, 3, 4, 5]).reshape(-1, 1)
c2 = np.array([0, 0, 0, 0, 0]).reshape(-1, 1)
c3 = np.array([-3, 3, 3, 5, 1]).reshape(-1, 1)
M = np.concatenate([c1, c2, c3], axis = 1).astype(float)
M

array([[ 1.,  0., -3.],
       [-1.,  0.,  3.],
       [ 3.,  0.,  3.],
       [ 4.,  0.,  5.],
       [ 5.,  0.,  1.]])

In [8]:
M[1] = M[1] + M[0]
M[2] = M[2] - 3*M[0]
M[3] = M[3] - 4*M[0]
M[4] = M[4] - 5*M[0]
M

array([[ 1.,  0., -3.],
       [ 0.,  0.,  0.],
       [ 0.,  0., 12.],
       [ 0.,  0., 17.],
       [ 0.,  0., 16.]])

In [9]:
M[[1, 4]] = M[[4, 1]]
M

array([[ 1.,  0., -3.],
       [ 0.,  0., 16.],
       [ 0.,  0., 12.],
       [ 0.,  0., 17.],
       [ 0.,  0.,  0.]])

In [10]:
M[1] = M[1]/16
M

array([[ 1.,  0., -3.],
       [ 0.,  0.,  1.],
       [ 0.,  0., 12.],
       [ 0.,  0., 17.],
       [ 0.,  0.,  0.]])

In [11]:
M[0] = M[0] + 3*M[1]
M[2] = M[2] - 12*M[1]
M[3] = M[3] - 17*M[1]
M

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

There are free variables so linearly dependent

Example of such scalars:

In [12]:
c1 = np.array([1, -1, 3, 4, 5]).reshape(-1, 1)
c2 = np.array([0, 0, 0, 0, 0]).reshape(-1, 1)
c3 = np.array([-3, 3, 3, 5, 1]).reshape(-1, 1)
M = np.concatenate([c1, c2, c3], axis = 1).astype(float)
M

array([[ 1.,  0., -3.],
       [-1.,  0.,  3.],
       [ 3.,  0.,  3.],
       [ 4.,  0.,  5.],
       [ 5.,  0.,  1.]])

In [13]:
M @ np.array([0, 20, 0]).reshape(-1, 1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])