# Elementary Row Operations

There are three types of elementary row operations that one can apply to a matrix.

1. Switch two rows.

M2. ultiply a row by a non-zero scalar.

Add a scalar multiple of one row to another row. (More precisely, replace one row with the sum of itself and a scalar multiple of a different row.)

In [1]:
import numpy as np

In [54]:
r1 = np.array([0, 1, -1, 1]).reshape(1,-1)
r2 = np.array([1, 2, -2, 1]).reshape(1,-1)
r3 = np.array([2, 6, -6, 4]).reshape(1,-1)
M = np.array([r1,r2,r3]).reshape(3,-1)
M

array([[ 0,  1, -1,  1],
       [ 1,  2, -2,  1],
       [ 2,  6, -6,  4]])

First, switch the first two rows.

In [55]:
M[[0,1]] = M[[1,0]]
M

array([[ 1,  2, -2,  1],
       [ 0,  1, -1,  1],
       [ 2,  6, -6,  4]])

Replace R3 with R3 - 2*R1

In [56]:
M[2] = M[2] - 2*M[0]
M

array([[ 1,  2, -2,  1],
       [ 0,  1, -1,  1],
       [ 0,  2, -2,  2]])

Next, replace R1 with R1 - 2*R2

In [57]:
M[0] = M[0] - 2*M[1]
M

array([[ 1,  0,  0, -1],
       [ 0,  1, -1,  1],
       [ 0,  2, -2,  2]])

Finally, replace R3 with R3 - 2*R2

In [58]:
M[2] = M[2] - 2*M[1]
M

array([[ 1,  0,  0, -1],
       [ 0,  1, -1,  1],
       [ 0,  0,  0,  0]])